FORMAT: 1A

# Finance App CRUD - API

Essa é a API do Finance App CRUD.

Nesta documentação você verá toda a especificação da API.

:::note
#### <i class="fa fa-info"></i> Importante
**A API está na versão 1, logo a rota deve iniciar com `/v1`**

Exemplo: `/v1/auth/register`
:::

# Group Authentication

Rotas relacionadas a autenticação.

<!-- include(auth/register.apib) -->

<!-- include(auth/login.apib) -->

<!-- include(auth/refresh.apib) -->
